spring.application.name=analytics

spring.datasource.url=jdbc:postgresql://localhost:5432/subway_analytics
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true